name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - development
          - staging
          - production
        required: true
        description: 'The environment root module to deploy.'
      noop:
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'
        required: true
        description: 'Noop (no operations) mode.'

concurrency:
  group: ${{ github.workflow }}-${{ github.event }}
  cancel-in-progress: true

jobs:
  terraform_scan:
    uses: ./.github/workflows/scan.yaml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    with:
      environment: ${{ inputs.environment }}

  terraform_test:
    uses: ./.github/workflows/test.yaml
    needs: terraform_scan
    secrets: inherit
    with:
      suite: 'all'
      environment: ${{ inputs.environment }}

  terraform_deploy:
    name: Deploy Infrastructure
    needs: terraform_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: az --version  # Example script to check Azure CLI version

      - name: Authenticate to Azure
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo $AZURE_CREDENTIALS > azure_credentials.json
          az login --service-principal --username $(jq -r .clientId azure_credentials.json) --password $(jq -r .clientSecret azure_credentials.json) --tenant $(jq -r .tenantId azure_credentials.json)

      - name: Set up Terraform environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "ARM_CLIENT_ID=$(jq -r .clientId azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenantId azure_credentials.json)" >> $GITHUB_ENV

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '>= 1.8, < 2.0'

      - name: Terraform init
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
        run: terraform init

      - name: Terraform plan
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
        run: terraform plan -out=tfplan -input=false

      - name: Terraform apply
        if: github.event.inputs.noop == 'false'
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
        run: terraform apply tfplan
